name: Build Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
      run: |
       ls -l
       echo 'Docker login'
       docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
       echo 'Running build...'
       docker build . -t mylorii/avenbot
       echo 'Pushing image...'
       docker push mylorii/avenbot
       echo 'Done!'
